export const initialState = {
    isOpened: false,
    reopen: false,
    rawData: [],
    data: [],
    invalidData: true,
    isLoading: true,
    maxHeight: 0,
    maxWidth: 0,
    minWidth: 0,
    inputValue: '',
    itemWidth: null,
    itemHeight: null,
    checkedItems: [],
    // filterValue: [],
    checkedItemsCounter: 0,
}