@startuml
class TableGrid {
    table: Object
    columns: Object[]
    globalFilter: Object
    getTableData()
    custom: Object
}
class table {
    width: number
    tableStriped: bool
    tableDark: bool
    tableBordered: bool
    tableBorderless: bool
    tableHover: bool
    globalFilter:bool
    renderRow()
    renderHeaderRow()
}
object custom {
    any custom key -> value
}
object filter << column filter config >> {
    filterBy: string|arrayOf[string]
    type: enum filterTypes
    allowedTypes: arrayOf[string]
}
object columns {
    title: string
    accessor: string
    minWidth: number
    maxWidth: number
    isVisible: bool
    filterable: bool
    filter: Object
}
object globalFilter {
    accessor: string|[string]
    type: enum filterTypes
    allowedTypes: arrayOf[string]
}
enum filterTypes {
    EQ
    NE
    LT
    LE
    GT
    GE
    STARTING
    ENDING
    LIST
}

TableGrid *-- table
TableGrid *-- columns
columns *-- filter
filter *-- filterTypes
globalFilter *-- filterTypes




@enduml